### ISSUE TITLE
spelling README.md

### ISSUE THREAD

**Issue by k4ss4n** [heathen-engineering/SteamworksFoundation#3]
https://github.com/heathen-engineering/SteamworksFoundation#features :
User **Daata** (easy access to user information, UI controls to display name, level, game status and more)

**Comment by XanIves** [comment]
Looks like there's another misspelling as well:

* Friends Interface (user names and avatar images, game info and friend chat, **frined** list UI controls)

Probably supposed to be "friend", not "frined".

**Comment by JamesMcGhee** [comment]
Think I have these all updated now
